gh pages workflow

diff --git a/.github/workflows/docs.yaml b/.github/workflows/docs.yaml
--- a/.github/workflows/docs.yaml
+++ b/.github/workflows/docs.yaml
@@ -9,7 +9,7 @@ on:
       - "main"
 
 jobs:
-  test:
+  build:
     name: Build Documentation
     runs-on: ubuntu-latest
 
@@ -22,8 +22,6 @@ jobs:
         uname -a
         df -h
         ulimit -a
-
-
     # More info on options: https://github.com/conda-incubator/setup-miniconda
     - uses: conda-incubator/setup-miniconda@v2
       with:
@@ -44,8 +42,6 @@ jobs:
       run: |
         python -m pip install . --no-deps
         conda list
-
-
     - name: Build Documentation
 
       # conda setup requires this special shell
@@ -55,4 +51,22 @@ jobs:
         cd docs
         make html
         cd ../
-
+    
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/janash/mit_workshop.git --branch gh-pages --single-branch gh-pages
+        cp -r docs/_build/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # the return code.
+    
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
